const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const plain=value=>JSON.parse(JSON.stringify(value));
function runtime(){let id=0;const c=vm.createContext({TextEncoder,crypto:{randomUUID:()=> 'id_'+(++id)}});for(const file of ['blueprint-model.js','learning-comparison.js','learning-preferences.js','learning-memory.js','learning-layout.js','layout.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist',file),'utf8'),c);c.SplitBlueprint={enabled:()=>false};return c;}
const format={id:'square',w:1080,h:1080},image={id:'logo',role:'logo',type:'image',asset:'logo_asset',aspect:2},images=new Map([['logo_asset',{width:200,height:100}]]);
function base(c,items=[image]){const result=c.SplitLayout.compose(format,plain(items));return{...format,bg:'#fff',composition:result.template,layers:plain(result.layers)};}
function learn(c,baseline,edit,planned=false){const m=c.SplitMemory;for(let i=0;i<3;i++){m.record('generation',[plain(baseline)],{images,planned});const final=plain(baseline);edit(final.layers[0]);m.record('export',[final],{images,planned});}return plain(m.snapshot().preferences);}
function run(c,items=[image],learning=c.SplitMemory.layoutLearning(),options={}){return plain(c.SplitLayout.compose(format,plain(items),undefined,{...options,learning}));}
function select(c,baseline,learning,extra={}){return plain(c.SplitLearningLayout.select([{name:'Test',layers:baseline.layers,score:10}],baseline,{learning,contextFor:c.SplitMemory.layoutContext,quality:()=>10,readable:()=>true,...extra}));}

test('empty, unavailable and provisional learning preserve the ordinary composition exactly',()=>{const c=runtime(),ordinary=run(c,[image],null);assert.deepEqual(run(c),ordinary);assert.deepEqual(run(c,[image],{project:{version:99},general:null}),ordinary);const b=base(c);c.SplitMemory.record('generation',[b],{images});const final=plain(b);final.layers[0].x+=.01;c.SplitMemory.record('export',[final],{images});assert.deepEqual(run(c),ordinary);});
test('confirmed preferences influence generation gradually within fixed bounds',()=>{const c=runtime(),b=base(c);learn(c,b,l=>l.x+=.01);const learned=run(c),before=run(c,[image],null);assert(learned.layers[0].x>before.layers[0].x);assert(learned.layers[0].x-before.layers[0].x<=.025);assert.equal(learned.layers[0].manualLayout,false);assert.deepEqual(run(c),learned);assert.equal(learned.template,b.composition);assert.equal(c.SplitMemory.snapshot().records.length,6);});
test('ready project preferences take precedence over the opposite general preference',()=>{const c=runtime(),b=base(c),own=learn(c,b,l=>l.x+=.01);c.SplitMemory.restore(null);const other=learn(c,b,l=>l.x-=.01),general=c.SplitPreferences.general([1,2,3].map(n=>({projectId:'p_'+n,preferences:other})));const learned=run(c,[image],{project:own,general});assert(learned.layers[0].x>b.layers[0].x);const fallback=run(c,[image],{project:c.SplitPreferences.empty(),general});assert(fallback.layers[0].x<b.layers[0].x);});
test('independent local confirmations without corrections suppress an incompatible general preference',()=>{const c=runtime(),b=base(c),other=learn(c,b,l=>l.x+=.01),general=c.SplitPreferences.general([1,2,3].map(n=>({projectId:'p_'+n,preferences:other})));c.SplitMemory.restore(null);const own=learn(c,b,()=>{});assert.deepEqual(run(c,[image],{project:own,general}),run(c,[image],null));});
test('context matching excludes changed proportions, roles, image ratios and custom rules',()=>{const c=runtime(),b=base(c);learn(c,b,l=>l.x+=.01);for(const item of [{...image,role:'cta'},{...image,aspect:4},{...image,rules:{position:'top'}},{...image,rules:{minWidth:20}}])assert.deepEqual(run(c,[item]),run(c,[item],null));const f={...format,h:1920};assert.deepEqual(plain(c.SplitLayout.compose(f,[image],undefined,{learning:c.SplitMemory.layoutLearning()})),plain(c.SplitLayout.compose(f,[image])));});
test('manual, locked, grouped and hidden layers never receive learned adjustments',()=>{const c=runtime(),b=base(c);learn(c,b,l=>l.x+=.01);for(const flag of ['manualLayout','locked','groupId','hidden']){const item={...b.layers[0],[flag]:flag==='groupId'?'group':true};assert.deepEqual(run(c,[item]),run(c,[item],null));}});
test('learned positions cannot escape the canvas or create a collision with another layer',()=>{const c=runtime(),b={...format,bg:'#fff',composition:'Test',layers:[{...image,x:.69,y:.1,w:.3,h:.2}]};learn(c,b,l=>l.x-=.1);const pref=c.SplitMemory.layoutLearning();const edge={...b,layers:[{...b.layers[0],x:0}]};assert.deepEqual(select(c,edge,pref).layers,edge.layers);const obstacle={id:'other',role:'text',type:'text',text:'text',x:.395,y:.1,w:.005,h:.2,fontSize:10,align:'left',manualLayout:true};const two={...b,layers:[{...b.layers[0],x:.4},obstacle]};const contextFor=(f,l)=>c.SplitMemory.layoutContext({...f,layers:[l]},l,false);assert.deepEqual(select(c,two,pref,{contextFor}).layers,two.layers);});
test('rotated bounds are checked before selecting a learned variant',()=>{const c=runtime(),b={...format,bg:'#fff',composition:'Test',layers:[{...image,x:.005,y:.1,w:.3,h:.2,rotation:0}]};learn(c,b,l=>l.rotation=10);const selected=select(c,b,c.SplitMemory.layoutLearning());const box=c.SplitLearningLayout.bounds(selected.layers[0],b);assert(box.x>=-1e-7);assert(box.y>=-1e-7);assert(Math.abs(selected.layers[0].rotation||0)<=3);});
test('image scaling preserves the original box proportion and fitting mode',()=>{const c=runtime(),b=base(c);learn(c,b,l=>{l.w*=1.1;l.h*=1.1;});const learned=run(c),normal=run(c,[image],null);assert(learned.layers[0].w>normal.layers[0].w);assert(Math.abs(learned.layers[0].w/learned.layers[0].h-normal.layers[0].w/normal.layers[0].h)<1e-8);assert.equal(learned.layers[0].fit,normal.layers[0].fit);});
test('planning keeps exact geometry while allowing safe text presentation preferences',()=>{const c=runtime(),area={x:.1,y:.1,w:.6,h:.5},text={id:'text',role:'text',type:'text',text:'Short title',align:'left'};c.SplitBlueprint={enabled:()=>true,itemMode:()=>true,template:()=>({text:{...area,sourceId:'text'}}),label:()=> 'Test'};const b=base(c,[text]);learn(c,b,l=>{l.x+=.01;l.fontSize*=.9;l.align='center';},true);const normal=run(c,[text],null,{expandBlueprint:true}),learned=run(c,[text],undefined,{expandBlueprint:true});assert.equal(learned.layers[0].x,normal.layers[0].x);assert.equal(learned.layers[0].y,normal.layers[0].y);assert.equal(learned.layers[0].w,normal.layers[0].w);assert.equal(learned.layers[0].h,normal.layers[0].h);assert.equal(learned.layers[0].align,'center');assert(learned.layers[0].fontSize<normal.layers[0].fontSize);assert.equal(learned.layers[0].layoutConflict,false);});
test('text overflow and unacceptable quality loss fall back to the ordinary composition',()=>{const c=runtime(),b={...format,bg:'#fff',composition:'Test',layers:[{id:'offer',role:'offer',type:'offer',text:'Offer',fontSize:40,align:'left',x:.1,y:.1,w:.6,h:.2}]};learn(c,b,l=>l.fontSize*=1.2);const learning=c.SplitMemory.layoutLearning();assert.deepEqual(select(c,b,learning,{readable:()=>false}).layers,b.layers);assert.deepEqual(select(c,b,learning,{quality:()=>9}).layers,b.layers);});
test('render and content recalculation stay unchanged unless learning is explicitly requested',()=>{const c=runtime(),b=base(c);learn(c,b,l=>l.x+=.01);assert.deepEqual(plain(c.SplitLayout.compose(format,[image])),run(c,[image],null));const model=plain(c.SplitMemory.snapshot().preferences);for(let i=0;i<5;i++){const result=run(c);c.SplitMemory.record('generation',[{...format,bg:'#fff',composition:result.template,layers:result.layers}],{images});}assert.deepEqual(plain(c.SplitMemory.snapshot().preferences),model);});

test('unchanged personalized exports do not reinforce or weaken the applied preference',()=>{const c=runtime(),b=base(c);learn(c,b,l=>l.x+=.01);const before=plain(c.SplitMemory.snapshot().preferences.entries.find(e=>e.metric==='x')),result=run(c),out={...format,bg:'#fff',composition:result.template,layers:result.layers};c.SplitMemory.markLayout(out,result.learningApplied);c.SplitMemory.record('generation',[out],{images});c.SplitMemory.record('export',[out],{images});const after=plain(c.SplitMemory.snapshot().preferences.entries.find(e=>e.metric==='x'));assert.deepEqual(after,before);const memory=plain(c.SplitMemory.snapshot());c.SplitMemory.restore(memory);assert.deepEqual(plain(c.SplitMemory.snapshot().preferences.entries.find(e=>e.metric==='x')),before);out.layers[0].x+=.003;c.SplitMemory.record('save',[out],{images});assert.equal(c.SplitMemory.snapshot().preferences.entries.find(e=>e.metric==='x').support,4);});

test('automatic rotation and alignment never accumulate across repeated recalculation or reopening',()=>{const c=runtime(),items=[{id:'offer',role:'offer',type:'offer',text:'Offer',align:'left'}],b=base(c,items);learn(c,b,l=>{l.rotation=3;l.align='center';});let result=run(c,items),first=plain(result.layers[0]);assert.equal(first.align,'center');for(let i=0;i<5;i++){const out={...format,bg:'#fff',composition:result.template,layers:result.layers};c.SplitMemory.markLayout(out,result.learningApplied);c.SplitMemory.record('generation',[out],{images});c.SplitMemory.restore(plain(c.SplitMemory.snapshot()));const inputs=result.layers.map(l=>c.SplitMemory.layoutInput(out,l));result=run(c,inputs);assert.equal(result.layers[0].rotation,first.rotation);assert.equal(result.layers[0].align,first.align);assert(result.learningApplied.some(entry=>entry.metrics.includes('align')));}});
