const test=require('node:test'),assert=require('node:assert/strict');
require('../dist/learning-comparison.js');require('../dist/learning-preferences.js');require('../dist/learning-memory.js');require('../dist/blueprint-model.js');require('../dist/layout.js');require('../dist/project-codec.js');
const model=SplitBlueprintModel,box={x:.1,y:.1,w:.3,h:.2};
const legacy=()=>({enabled:true,templates:Object.fromEntries(model.families.map(f=>[f,Object.fromEntries(model.types.map(role=>[role,{...box}]))]))});
const source=(id,role='image')=>({id,role,type:'image',aspect:2});
test('planned generation overrides prior geometry without displacing neighbors around locks',()=>{const template={image:{...box,sourceId:'a'},logo:{x:.6,y:.6,w:.3,h:.2,sourceId:'b'}};globalThis.SplitBlueprint={enabled:()=>true,itemMode:()=>true,template:()=>template,label:()=> 'Test'};const edited={...source('a'),manualLayout:true,rotation:90,x:.6,y:.6,w:.3,h:.2};const run=item=>SplitLayout.compose({w:1000,h:1000},[item,source('b','logo')],undefined,{expandBlueprint:true});const planned=run(edited);assert.equal(planned.layers[0].rotation,0);assert.equal(planned.layers[0].manualLayout,false);assert(planned.layers[0].x<.6);const locked=run({...edited,locked:true});assert.equal(locked.layers[0].x,.6);assert.equal(locked.layers[0].rotation,90);assert.equal(locked.layers[0].layoutConflict,true);assert.equal(locked.layers[1].x,planned.layers[1].x);assert.equal(locked.layers[1].y,planned.layers[1].y);});
test('missing planned content is reported even when there are no layers',()=>{globalThis.SplitBlueprint={enabled:()=>true,itemMode:()=>true,template:()=>({image:{...box,sourceId:'gone'}}),label:()=> 'Test'};const result=SplitLayout.compose({w:1000,h:1000},[],undefined,{expandBlueprint:true});assert.equal(result.layers.length,0);assert.equal(result.warnings.length,1);});
test('an existing duplicate survives recalculation after its original layer is removed',()=>{const template={'image-2':{...box,sourceId:'a'}};const duplicate={...source('bp_image-2_a'),blueprintSourceId:'a'};assert.equal(model.entries(template,[duplicate])[0].item.id,duplicate.id);});
test('old diagrams expand multiple sources into separate items and remain serializable',()=>{const plan=model.normalize(legacy(),[source('a'),source('b')]);assert(plan.itemMode);assert.equal(plan.templates.horizontal.image.sourceId,'a');assert.equal(plan.templates.horizontal['image-2'].sourceId,'b');assert.notEqual(plan.templates.horizontal.image.y,plan.templates.horizontal['image-2'].y);assert.deepEqual(model.normalize(plan,[source('c')]),plan);});
test('removed role produces no layer; other families remain independent',()=>{const plan=model.normalize(legacy(),[source('a'),source('button','cta')]);delete plan.templates.horizontal.cta;assert.deepEqual(model.entries(plan.templates.horizontal,[source('a'),source('button','cta')],true).map(e=>e.item.role),['image']);assert(plan.templates.vertical.cta);});
test('duplicate IDs stay stable when the first item is removed',()=>{const template={image:{...box,sourceId:'a'},'image-2':{...box,x:.6,sourceId:'a'}};const before=model.entries(template,[source('a')],true);delete template.image;const after=model.entries(template,[source('a')],true);assert.equal(after[0].item.id,before[1].item.id);assert.equal(after[0].item.blueprintSourceId,'a');assert.equal(model.entries(template,[source('a')]).length,0);});
test('generation fits each item into its own planned area without distortion',()=>{const template={image:{...box,sourceId:'a'},'image-2':{...box,x:.6,sourceId:'a'}};globalThis.SplitBlueprint={enabled:()=>true,itemMode:()=>true,template:()=>template,label:()=> 'Test'};const result=SplitLayout.compose({w:1000,h:1000},[source('a')],undefined,{expandBlueprint:true});assert.equal(result.layers.length,2);assert.equal(new Set(result.layers.map(l=>l.id)).size,2);for(const layer of result.layers){const area=template[layer.id==='a'?'image':'image-2'];assert(layer.x>=area.x&&layer.x+layer.w<=area.x+area.w+1e-9);assert(layer.y>=area.y&&layer.y+layer.h<=area.y+area.h+1e-9);assert.equal(layer.w,area.w);assert.equal(layer.h,area.h);assert.equal(layer.fit,'contain');assert.equal(layer.aspect,2);}});
test('project schema preserves empty diagrams, source bindings and old versions',()=>{const project={kind:'split-project',version:4,campaign:'Test',assets:[],formats:[{id:'square',name:'Square',w:1000,h:1000}],checked:['square'],sources:[],outputs:[],baseBackground:'#ffffff',selectedIds:[],view:'grid',blueprint:legacy()};assert.equal(SplitProject.validate(project).version,7);const plan=model.normalize(legacy());plan.templates.horizontal={};plan.templates.vertical['text-2']={...box,sourceId:'e4'};const saved=SplitProject.validate({...project,version:5,blueprint:plan});assert.deepEqual(saved.blueprint.templates.horizontal,{});assert.equal(saved.blueprint.templates.vertical['text-2'].sourceId,'e4');assert.throws(()=>SplitProject.validate({...project,blueprint:{...plan,templates:{...plan.templates,horizontal:{'bad-key':box}}}}));});

test('nearest proportional plan serves square and near-square formats using the vertical plan',()=>{assert.equal(model.classify(1080,1080),'vertical');assert.equal(model.classify(1100,1080),'vertical');assert.equal(model.classify(1200,628),'horizontal');assert.equal(model.classify(728,90),'wide');assert.equal(model.classify(300,1500),'tall');for(const [family,ratio] of Object.entries(model.ratios))assert.equal(model.classify(ratio*1000,1000),family);});

test('medium rectangles get a dedicated plan and older projects acquire it without changing other diagrams',()=>{assert.equal(model.classify(300,250),'medium');assert.equal(model.classify(600,500),'medium');const old=model.normalize(legacy());delete old.templates.medium;const migrated=model.normalize(old);assert.deepEqual(migrated.templates.horizontal,old.templates.horizontal);assert.equal(migrated.templates.medium.image.w,model.mediumDefault.image.w);});
