const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function planner(){
 const nodes=new Map(),ctx=new Proxy({}, {get:()=>()=>{}});
 function node(){return{children:[],dataset:{},listeners:{},width:800,height:520,value:'',append(...items){this.children.push(...items)},replaceChildren(){this.children=[]},setAttribute(){},querySelector(){return this.children[0]},getContext(){return ctx},getBoundingClientRect(){return{left:0,top:0,width:this.width,height:this.height}},setPointerCapture(){},addEventListener(name,fn){this.listeners[name]=fn},showModal(){},close(){this.listeners.close?.()},closest(){return null}};}
 const $=id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)};
 const sandbox={$ ,document:{documentElement:{dataset:{}},createElement:node},sources:[],outputs:[],clone:v=>structuredClone(v),clamp:(v,min,max)=>Math.max(min,Math.min(max,v)),current:()=>({w:1200,h:628}),SplitEditor:{finishInteraction(){}},SplitLayout:{overlap:()=>false},checkpoint(){},toast(){}};
 vm.createContext(sandbox);for(const file of ['blueprint-model.js','blueprint.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),sandbox);
 const api=sandbox.SplitBlueprint;api.open();return{api,$};
}
const blankTarget={closest:()=>null},deleteEvent=target=>({key:'Delete',target,preventDefault(){},stopPropagation(){}});
test('blank canvas deselects and Delete cannot remove an unselected item',()=>{const{api,$}=planner();api.start({button:0,clientX:0,clientY:0});assert.equal(api.selection().length,0);assert.equal($('blueprint-x').disabled,true);$('blueprintDialog').listeners.keydown(deleteEvent(blankTarget));assert(api.draft().templates.horizontal.image);api.update('image',{x:.2,y:.2,w:.2,h:.2});assert.equal(api.selection().length,0);});
test('Delete removes selected items, sets the last-item count to zero, and undo restores them',()=>{const{api,$}=planner();$('blueprintDialog').listeners.keydown(deleteEvent(blankTarget));assert.equal(api.selection().length,0);assert.equal(api.draft().templates.horizontal.image,undefined);const group=$('blueprintRoles').children.find(g=>g.dataset.type==='image');assert.equal(group.children[2].textContent,0);api.undo();assert(api.draft().templates.horizontal.image);assert.equal(api.selection().length,0);});
test('Delete inside a field does not delete diagram items; whitespace clears selection',()=>{const{api,$}=planner();$('blueprintDialog').listeners.keydown(deleteEvent({closest:()=>({})}));assert(api.draft().templates.horizontal.image);$('blueprintDialog').listeners.pointerdown({button:0,target:blankTarget});assert.equal(api.selection().length,0);});
test('Delete removes a multiple selection in one undo step',()=>{const{api,$}=planner();$('blueprintMulti').onclick();const logo=$('blueprintRoles').children.find(g=>g.dataset.type==='logo');logo.children[0].onclick({});assert.equal(api.selection().length,2);$('blueprintDialog').listeners.keydown(deleteEvent(blankTarget));assert.equal(api.draft().templates.horizontal.logo,undefined);assert.equal(api.draft().templates.horizontal.image,undefined);api.undo();assert(api.draft().templates.horizontal.logo);assert(api.draft().templates.horizontal.image);});
